# Basic project details.
site_name: 'FinNexus Documentation'
site_description: 'Decentralized Protocol Clusters'
site_author: 'FinNexus Team'
site_url: ''

# Links to the core FinNexus smart contract repository.
repo_name: 'FinNexus'
repo_url: 'https://github.com/FinNexus'

# Setting `edit_uri` to an empty string disables the edit button, which points to the wrong page.
# If at some point this documentation is moved into the core  repository, then this can be
# removed.
edit_uri: ''

docs_dir: 'content'


# Top level headings become tabs at the top due to `tabs: true` in the theme.
nav:
  - Introduction: index.md
  - About FinNexus: 
    - Product Paper: about/productpaper.md
    - Whitepapers(old): about/papers.md
    - Official Links: about/links.md
    - Media Coverage: about/coverage.md
  - Guides:
    - How to buy options: guides/buyoptions.md
    - How to Mine (FPO): guides/mining-fpo.md
  - Products: 
    - Introduction: products/index.md
    - Derivatives:
      - FinNexus Protocol for Options (FPO): products/options.md
    - Gaming:
      - Jack's Pot: products/jackspot.md
      - Wandora Box: products/wandora.md
    - Liquidity mining:
      - AMM Liquidity Mining: products/liquidity.md
  - Options Protocol (FPO):
    - Options Basics:  options/index.md
    - Options Key Terms:  options/terms.md
    - Options Strategies: options/strategies.md
    - FPO v0.1:  options/v0.1.md
    - FPO v0.1 Smart Contracts:  options/contracts.md
    - FPO v1.0:  options/v1.0.md
    - Returns in the pool: options/financials.md
    - Risks in FPO v1.0: options/risks.md
    - Making FPO v1.0 Secure: options/security.md
    
  - FinNexus Token (FNX): 
    - Addresses: token/addresses.md
    - Token Distribution: token/index.md
    - How to get FNX: token/markets.md
    - FNX mining: token/mining-fpo.md
    - Add FNX to Wanchain Wallet: token/add_fnx.md
  - Governance: 
    - Overview: governance/index.md
  - Developers:
    - Overview:  developers/index.md
    - FNX Token API v0.1 Alpha:  developers/token-api.md
    - Smart Contracts:  developers/smart-contracts.md
  - Terminology:
    - Overview:  terminology/index.md
    - DeFi Terms: terminology/defi.md
    - Options Terms: terminology/options.md
    - FPO Terms:  terminology/fpo.md
  - In-depth Reading: 
    - English: indepthreading/english.md
    - Chinese: indepthreading/chinese.md

  

 
# These social links will be rendered as icons in the footer, as long as the type corresponds to FontAwesome glyph.
extra:
  extra_javascript:
    - js/image_zoom.js
  social:
    - icon: 'brands/github'
      link: 'https://github.com/FinNexus'
    - icon: 'brands/twitter'
      link: 'https://twitter.com/fin_nexus'
    - icon: 'brands/reddit'
      link: 'https://www.reddit.com/r/finnexus/'
    - icon: 'brands/medium'
      link: 'https://medium.com/finnexus/'
    - icon: 'brands/discord'
      link: 'https://discord.gg/bCDMHN7'

# This set of documentation uses the MkDocs Material theme by squidfunk: https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'deep purple'
  logo: 'img/logos/square.png'
  favicon: 'img/favicon.ico'
  feature:
    tabs: false
    instant: false
    sections: true
    expand: true
    
    


plugins:
    - search
    

# Extension settings.
# In addition to the standard extensions, this also requires the PyMdown Extensions by facelessuser: https://github.com/facelessuser/pymdown-extensions
markdown_extensions:
  - toc:
      permalink: True # Generates permanent links for each page section.
      toc_depth: 10
  - admonition # Small descriptive elements for notes, warnings, etc.
  - pymdownx.arithmatex # Math rendering.
  - pymdownx.tasklist: # Allows nested and better checkboxes.
      custom_checkbox: True # Without this setting, checkboxes look rubbish in the material theme.
  - pymdownx.highlight: # Code syntax highlighting.
      linenums: True
  - pymdownx.extra: # Better fenced code blocks, emphasis, footnotes, lists, tables, abbreviations, and raw HTML.
      pymdownx.betterem:
        smart_enable: 'all' # Smarter line breaks when emphasising lines.
  - pymdownx.details # Collapsible admonition-style blocks containing further information.
  - pymdownx.escapeall # Backslashes escape everything.
  - pymdownx.caret # Superscripts and insert text.
  - pymdownx.superfences
  - pymdownx.tabbed # tabs
  - pymdownx.tilde # Strikethrough and underlines.
  - pymdownx.magiclink: # Better links and github references.
      provider: 'github'
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: 'noahniuwa'
      repo: 'fnx_docs'
 
